// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtJMmimwZSgW8FXM_kbZqbItcDlgQxVaE',
    appId: '1:20585779352:web:3797104481dd258c4e40ed',
    messagingSenderId: '20585779352',
    projectId: 'weather-go-1c7f3',
    authDomain: 'weather-go-1c7f3.firebaseapp.com',
    storageBucket: 'weather-go-1c7f3.firebasestorage.app',
    measurementId: 'G-EGY5PDNC2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ6veP1QHoIQy3mIhQwu5ousmPYlzgY_s',
    appId: '1:20585779352:android:c122319890d1791b4e40ed',
    messagingSenderId: '20585779352',
    projectId: 'weather-go-1c7f3',
    storageBucket: 'weather-go-1c7f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwt-aXFBr9XkgeU6hEuX3eBj8oMODwLdg',
    appId: '1:20585779352:ios:f887d5a8ae4f654b4e40ed',
    messagingSenderId: '20585779352',
    projectId: 'weather-go-1c7f3',
    storageBucket: 'weather-go-1c7f3.firebasestorage.app',
    iosBundleId: 'com.example.weatherGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwt-aXFBr9XkgeU6hEuX3eBj8oMODwLdg',
    appId: '1:20585779352:ios:f887d5a8ae4f654b4e40ed',
    messagingSenderId: '20585779352',
    projectId: 'weather-go-1c7f3',
    storageBucket: 'weather-go-1c7f3.firebasestorage.app',
    iosBundleId: 'com.example.weatherGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtJMmimwZSgW8FXM_kbZqbItcDlgQxVaE',
    appId: '1:20585779352:web:68d8a2e2ecb7cf1c4e40ed',
    messagingSenderId: '20585779352',
    projectId: 'weather-go-1c7f3',
    authDomain: 'weather-go-1c7f3.firebaseapp.com',
    storageBucket: 'weather-go-1c7f3.firebasestorage.app',
    measurementId: 'G-GREV1YJ6LK',
  );
}
